Repository Gongspot/Gongspot_Server, pull requests merged in 2025-07, with the labels that each got.

#2 [FEAT] Custom OAuth + JWT 로그인 방식 구현, closes #1
  src/main/java/com/gongspot/project/global/auth/CustomOAuth2SuccessHandler.java
  src/main/java/com/gongspot/project/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/gongspot/project/global/auth/JwtTokenProvider.java
  src/main/java/com/gongspot/project/global/config/SecurityConfig.java
  src/main/java/com/gongspot/project/global/config/SwaggerConfig.java
  src/main/resources/application.properties
Labels: enhancement

#27 [CORE] github actions 테스트
  .github/workflows/deploy.yml
  src/main/java/com/gongspot/project/global/config/SwaggerConfig.java
  src/main/resources/application.properties
Labels: 🌏 Deploy

#14 [FEAT] HOT한 학습 공간 조회 API 구현
  src/main/generated/com/gongspot/project/domain/home/entity/QHotCheck.java
  src/main/generated/com/gongspot/project/domain/place/entity/QPlace.java
  src/main/java/com/gongspot/project/domain/home/controller/HomeController.java
  src/main/java/com/gongspot/project/domain/home/converter/HomeConverter.java
  src/main/java/com/gongspot/project/domain/home/dto/HomeResponseDTO.java
  src/main/java/com/gongspot/project/domain/home/entity/HotCheck.java
  src/main/java/com/gongspot/project/domain/home/repository/HomeRepository.java
  src/main/java/com/gongspot/project/domain/home/repository/HomeRepositoryCustom.java
  src/main/java/com/gongspot/project/domain/home/repository/HomeRepositoryImpl.java
  src/main/java/com/gongspot/project/domain/home/service/HomeQueryService.java
  src/main/java/com/gongspot/project/domain/home/service/HomeQueryServiceImpl.java
  src/main/java/com/gongspot/project/domain/place/entity/Place.java
  src/main/resources/application.properties
Labels: 📬 API, ✨ Feature

#16 [FEAT] 공지사항 목록조회 api 구현 , closes #15
  src/main/java/com/gongspot/project/common/code/status/ErrorStatus.java
  src/main/java/com/gongspot/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gongspot/project/domain/notification/converter/NotificationConverter.java
  src/main/java/com/gongspot/project/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/com/gongspot/project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gongspot/project/domain/notification/service/NotificationQueryService.java
  src/main/java/com/gongspot/project/domain/notification/service/NotificationQueryServiceImpl.java
Labels: 📬 API, ✨ Feature

#23 [FEAT] 포인트 내역 조회 API 구현
  src/main/java/com/gongspot/project/domain/point/controller/PointController.java
  src/main/java/com/gongspot/project/domain/point/converter/PointConverter.java
  src/main/java/com/gongspot/project/domain/point/dto/PageInfo.java
  src/main/java/com/gongspot/project/domain/point/dto/PageResponse.java
  src/main/java/com/gongspot/project/domain/point/dto/PointHistoryDTO.java
  src/main/java/com/gongspot/project/domain/point/repository/PointRepository.java
  src/main/java/com/gongspot/project/domain/point/service/PointQueryService.java
  src/main/java/com/gongspot/project/domain/point/service/PointQueryServiceImpl.java
  src/main/resources/application.properties
Labels: 📬 API, ✨ Feature

#41 [FEAT] 새 공간 등록 신청 API, closes #39
  src/main/java/com/gongspot/project/domain/newplace/controller/NewPlaceController.java
  src/main/java/com/gongspot/project/domain/newplace/dto/NewPlaceRequestDTO.java
  src/main/java/com/gongspot/project/domain/newplace/dto/NewPlaceResponseDTO.java
  src/main/java/com/gongspot/project/domain/newplace/entity/NewPlace.java
  src/main/java/com/gongspot/project/domain/newplace/repository/NewPlaceRepository.java
  src/main/java/com/gongspot/project/domain/newplace/service/NewPlaceCommandService.java
  src/main/java/com/gongspot/project/domain/newplace/service/NewPlaceCommandServiceImpl.java
Labels: 📬 API, ✨ Feature

#33 [FEAT] 찜한 공간 목록 조회 api 구현 , closes #31
  src/main/generated/com/gongspot/project/domain/place/entity/QPlace.java
  src/main/java/com/gongspot/project/domain/like/converter/LikeConverter.java
  src/main/java/com/gongspot/project/domain/like/dto/LikeResponseDTO.java
  src/main/java/com/gongspot/project/domain/like/repository/LikeRepository.java
  src/main/java/com/gongspot/project/domain/like/service/LikeQueryService.java
  src/main/java/com/gongspot/project/domain/like/service/LikeQueryServiceImpl.java
  src/main/java/com/gongspot/project/domain/media/repository/MediaRepository.java
  src/main/java/com/gongspot/project/domain/place/controller/PlaceController.java
  src/main/java/com/gongspot/project/domain/place/converter/PlaceConverter.java
  src/main/java/com/gongspot/project/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/gongspot/project/domain/place/entity/Place.java
Labels: 📬 API, ✨ Feature

#55 [CI/CD] update deploy.yml
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#56 [CI/CD] update deploy.yml
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#57 [CI/CD] 서버 배포용 PR
  .github/workflows/deploy.yml
  src/main/java/com/gongspot/project/domain/place/controller/PlaceController.java
Labels: 🌏 Deploy

#61 [FEAT] 구글맵 링크 기반 장소 등록 API, closes #59
  build.gradle
  src/main/generated/com/gongspot/project/domain/place/entity/QPlace.java
  src/main/generated/com/gongspot/project/domain/user/entity/QUser.java
  src/main/java/com/gongspot/project/common/code/status/ErrorStatus.java
  src/main/java/com/gongspot/project/common/enums/RoleEnum.java
  src/main/java/com/gongspot/project/common/exception/ExceptionAdvice.java
  src/main/java/com/gongspot/project/domain/newplace/controller/NewPlaceController.java
  src/main/java/com/gongspot/project/domain/newplace/service/GoogleMapsService.java
  src/main/java/com/gongspot/project/domain/newplace/service/GoogleMapsServiceImpl.java
  src/main/java/com/gongspot/project/domain/place/controller/PlaceController.java
  src/main/java/com/gongspot/project/domain/place/converter/PlaceConverter.java
  src/main/java/com/gongspot/project/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/gongspot/project/domain/place/entity/Place.java
  src/main/java/com/gongspot/project/domain/place/service/GooglePlaceDetailService.java
  src/main/java/com/gongspot/project/domain/place/service/GooglePlaceDetailServiceImpl.java
  src/main/java/com/gongspot/project/domain/user/entity/User.java
  src/main/java/com/gongspot/project/global/auth/JwtTokenProvider.java
  src/main/java/com/gongspot/project/global/auth/oauth/CustomAccessDeniedHandler.java
  src/main/java/com/gongspot/project/global/auth/oauth/CustomOAuth2UserService.java
  src/main/java/com/gongspot/project/global/auth/service/TokenService.java
  src/main/java/com/gongspot/project/global/config/CorsConfig.java
  src/main/java/com/gongspot/project/global/config/SecurityConfig.java
  src/main/java/com/gongspot/project/global/config/SwaggerConfig.java
  src/main/resources/application.properties
Labels: 📬 API, 🔨 Refactor, ✨ Feature

#70 [FEAT] 공간 검색 API 구현
  src/main/java/com/gongspot/project/domain/place/controller/PlaceController.java
  src/main/java/com/gongspot/project/domain/place/converter/PlaceConverter.java
  src/main/java/com/gongspot/project/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/gongspot/project/domain/place/entity/Place.java
  src/main/java/com/gongspot/project/domain/place/repository/PlaceRepository.java
  src/main/java/com/gongspot/project/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/gongspot/project/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/gongspot/project/domain/place/service/PlaceQueryService.java
  src/main/java/com/gongspot/project/domain/place/service/PlaceQueryServiceImpl.java
  src/main/java/com/gongspot/project/domain/search/entity/RecentSearch.java
Labels: 📬 API, ✨ Feature

#67 [REFACTOR] 공간 요청 승인으로 필터링하도록 리팩토링
  src/main/generated/com/gongspot/project/domain/newplace/entity/QNewPlace.java
  src/main/java/com/gongspot/project/common/code/status/ErrorStatus.java
  src/main/java/com/gongspot/project/domain/newplace/controller/NewPlaceController.java
  src/main/java/com/gongspot/project/domain/newplace/entity/NewPlace.java
  src/main/java/com/gongspot/project/domain/newplace/repository/NewPlaceRepository.java
  src/main/java/com/gongspot/project/domain/newplace/service/NewPlaceCommandService.java
  src/main/java/com/gongspot/project/domain/newplace/service/NewPlaceCommandServiceImpl.java
  src/main/java/com/gongspot/project/domain/place/converter/PlaceConverter.java
  src/main/java/com/gongspot/project/domain/place/dto/PlaceResponseDTO.java
Labels: 📬 API, 🔨 Refactor

#42 [FEAT] 공간 리뷰 작성 API 구현
  build.gradle
  src/main/java/com/gongspot/project/common/code/status/ErrorStatus.java
  src/main/java/com/gongspot/project/common/exception/ExceptionAdvice.java
  src/main/java/com/gongspot/project/domain/home/entity/HotCheck.java
  src/main/java/com/gongspot/project/domain/home/repository/HomeRepositoryCustom.java
  src/main/java/com/gongspot/project/domain/home/repository/HomeRepositoryImpl.java
  src/main/java/com/gongspot/project/domain/home/repository/HotCheckRepository.java
  src/main/java/com/gongspot/project/domain/home/service/HomeCommandService.java
  src/main/java/com/gongspot/project/domain/home/service/HomeCommandServiceImpl.java
  src/main/java/com/gongspot/project/domain/review/controller/ReviewController.java
  src/main/java/com/gongspot/project/domain/review/converter/ReviewConverter.java
  src/main/java/com/gongspot/project/domain/review/dto/ReviewRequestDTO.java
  src/main/java/com/gongspot/project/domain/review/entity/Review.java
  src/main/java/com/gongspot/project/domain/review/repository/ReviewRepository.java
  src/main/java/com/gongspot/project/domain/review/service/ReviewCommandService.java
  src/main/java/com/gongspot/project/domain/review/service/ReviewCommandServiceImpl.java
  src/main/java/com/gongspot/project/domain/review/service/ReviewQueryService.java
  src/main/java/com/gongspot/project/domain/review/service/ReviewQueryServiceImpl.java
  src/main/java/com/gongspot/project/domain/user/entity/User.java
  src/main/java/com/gongspot/project/global/auth/service/CustomOAuth2UserService.java
  src/main/java/com/gongspot/project/global/config/SecurityConfig.java
  src/main/resources/application.properties
Labels: 📬 API, ✨ Feature
