Repository Gongspot/Gongspot_Server, pull requests merged in 2025-08, with the labels that each got.

#82 [CI/CD] Deploy to ec2
  src/main/java/com/gongspot/project/global/config/CorsConfig.java
Labels: 🌏 Deploy

#79 [FEAT] 공지사항 등록 api 구현 , closes #60
  build.gradle
  src/main/generated/com/gongspot/project/domain/banner/entity/QBanner.java
  src/main/generated/com/gongspot/project/domain/media/entity/QMedia.java
  src/main/generated/com/gongspot/project/domain/notification/entity/QNotification.java
  src/main/generated/com/gongspot/project/domain/uuid/entity/QUuid.java
  src/main/java/com/gongspot/project/common/code/status/ErrorStatus.java
  src/main/java/com/gongspot/project/domain/banner/controller/BannerController.java
  src/main/java/com/gongspot/project/domain/banner/converter/BannerConverter.java
  src/main/java/com/gongspot/project/domain/banner/dto/BannerResponseDTO.java
  src/main/java/com/gongspot/project/domain/banner/entity/Banner.java
  src/main/java/com/gongspot/project/domain/banner/repository/BannerRepository.java
  src/main/java/com/gongspot/project/domain/banner/repository/BannerRepositoryCustom.java
  src/main/java/com/gongspot/project/domain/banner/repository/BannerRepositoryImpl.java
  src/main/java/com/gongspot/project/domain/banner/service/BannerQueryService.java
  src/main/java/com/gongspot/project/domain/banner/service/BannerQueryServiceImpl.java
  src/main/java/com/gongspot/project/domain/media/entity/Media.java
  src/main/java/com/gongspot/project/domain/media/repository/MediaRepository.java
  src/main/java/com/gongspot/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gongspot/project/domain/notification/converter/NotificationConverter.java
  src/main/java/com/gongspot/project/domain/notification/dto/NotificationRequestDTO.java
  src/main/java/com/gongspot/project/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/com/gongspot/project/domain/notification/entity/Notification.java
  src/main/java/com/gongspot/project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gongspot/project/domain/notification/service/NotificationCommandService.java
  src/main/java/com/gongspot/project/domain/notification/service/NotificationCommandServiceImpl.java
  src/main/java/com/gongspot/project/domain/notification/service/NotificationQueryService.java
  src/main/java/com/gongspot/project/domain/notification/service/NotificationQueryServiceImpl.java
  src/main/java/com/gongspot/project/domain/uuid/entity/Uuid.java
  src/main/java/com/gongspot/project/domain/uuid/repository/UuidRepository.java
  src/main/java/com/gongspot/project/global/aws/s3/AmazonS3Manager.java
  src/main/java/com/gongspot/project/global/config/AmazonConfig.java
  src/main/java/com/gongspot/project/global/config/SecurityConfig.java
  src/main/resources/application.properties
Labels: 📬 API, ✨ Feature

#83 [CI/CD] Deploy to ec2
  build.gradle
  src/main/generated/com/gongspot/project/domain/banner/entity/QBanner.java
  src/main/generated/com/gongspot/project/domain/media/entity/QMedia.java
  src/main/generated/com/gongspot/project/domain/notification/entity/QNotification.java
  src/main/generated/com/gongspot/project/domain/uuid/entity/QUuid.java
  src/main/java/com/gongspot/project/common/code/status/ErrorStatus.java
  src/main/java/com/gongspot/project/domain/banner/controller/BannerController.java
  src/main/java/com/gongspot/project/domain/banner/converter/BannerConverter.java
  src/main/java/com/gongspot/project/domain/banner/dto/BannerResponseDTO.java
  src/main/java/com/gongspot/project/domain/banner/entity/Banner.java
  src/main/java/com/gongspot/project/domain/banner/repository/BannerRepository.java
  src/main/java/com/gongspot/project/domain/banner/service/BannerQueryService.java
  src/main/java/com/gongspot/project/domain/banner/service/BannerQueryServiceImpl.java
  src/main/java/com/gongspot/project/domain/media/entity/Media.java
  src/main/java/com/gongspot/project/domain/media/repository/MediaRepository.java
  src/main/java/com/gongspot/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gongspot/project/domain/notification/converter/NotificationConverter.java
  src/main/java/com/gongspot/project/domain/notification/dto/NotificationRequestDTO.java
  src/main/java/com/gongspot/project/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/com/gongspot/project/domain/notification/entity/Notification.java
  src/main/java/com/gongspot/project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gongspot/project/domain/notification/service/NotificationCommandService.java
  src/main/java/com/gongspot/project/domain/notification/service/NotificationCommandServiceImpl.java
  src/main/java/com/gongspot/project/domain/notification/service/NotificationQueryService.java
  src/main/java/com/gongspot/project/domain/notification/service/NotificationQueryServiceImpl.java
  src/main/java/com/gongspot/project/domain/uuid/entity/Uuid.java
  src/main/java/com/gongspot/project/domain/uuid/repository/UuidRepository.java
  src/main/java/com/gongspot/project/global/aws/s3/AmazonS3Manager.java
  src/main/java/com/gongspot/project/global/config/AmazonConfig.java
  src/main/java/com/gongspot/project/global/config/SecurityConfig.java
  src/main/resources/application.properties
Labels: 🌏 Deploy

#88 [FEAT] 공지사항 삭제, 배너 수정,삭제 api 구현 , closes #87
  src/main/java/com/gongspot/project/domain/banner/controller/BannerController.java
  src/main/java/com/gongspot/project/domain/banner/converter/BannerConverter.java
  src/main/java/com/gongspot/project/domain/banner/dto/BannerRequestDTO.java
  src/main/java/com/gongspot/project/domain/banner/service/BannerCommandService.java
  src/main/java/com/gongspot/project/domain/banner/service/BannerCommandServiceImpl.java
  src/main/java/com/gongspot/project/domain/media/entity/Media.java
  src/main/java/com/gongspot/project/domain/media/repository/MediaRepository.java
  src/main/java/com/gongspot/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gongspot/project/domain/notification/converter/NotificationConverter.java
  src/main/java/com/gongspot/project/domain/notification/entity/Notification.java
  src/main/java/com/gongspot/project/domain/notification/service/NotificationCommandService.java
  src/main/java/com/gongspot/project/domain/notification/service/NotificationCommandServiceImpl.java
Labels: 📬 API, ✨ Feature

#94 [Refactor] 방문한 공간 목록 조회 api 기능 수정
  src/main/java/com/gongspot/project/domain/place/converter/PlaceConverter.java
  src/main/java/com/gongspot/project/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/gongspot/project/domain/place/service/PlaceQueryServiceImpl.java
Labels: 🔨 Refactor

#97 [FEAT]: 프로필 사진, 닉네임 조회 api - 프로필 사진 파일 형식으로 수정
  src/main/java/com/gongspot/project/common/code/status/ErrorStatus.java
  src/main/java/com/gongspot/project/domain/user/controller/UserController.java
  src/main/java/com/gongspot/project/domain/user/dto/UserRequestDTO.java
  src/main/java/com/gongspot/project/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/gongspot/project/global/auth/service/S3UploadService.java
  src/main/java/com/gongspot/project/global/config/AmazonConfig.java
  src/main/resources/application.properties
Labels: 🔨 Refactor

#98 [FEAT]: 최근 검색어 조회 api - id와 keyword를 함께 받도록 수정
  src/main/java/com/gongspot/project/domain/search/converter/RecentSearchConverter.java
  src/main/java/com/gongspot/project/domain/search/dto/RecentSearchResponseDTO.java
  src/main/java/com/gongspot/project/domain/search/service/RecentSearchQueryServiceImpl.java
Labels: 🔨 Refactor

#106 [CI/CD] Deploy to EC2
  src/main/generated/com/gongspot/project/domain/newplace/entity/QNewPlace.java
  src/main/java/com/gongspot/project/common/code/status/ErrorStatus.java
  src/main/java/com/gongspot/project/domain/newplace/controller/NewPlaceController.java
  src/main/java/com/gongspot/project/domain/newplace/converter/NewPlaceConverter.java
  src/main/java/com/gongspot/project/domain/newplace/dto/NewPlaceResponseDTO.java
  src/main/java/com/gongspot/project/domain/newplace/entity/NewPlace.java
  src/main/java/com/gongspot/project/domain/newplace/repository/NewPlaceRepository.java
  src/main/java/com/gongspot/project/domain/newplace/service/NewPlaceCommandService.java
  src/main/java/com/gongspot/project/domain/newplace/service/NewPlaceCommandServiceImpl.java
  src/main/java/com/gongspot/project/domain/review/dto/ReviewRequestDTO.java
  src/main/java/com/gongspot/project/global/config/CorsConfig.java
  src/main/resources/application.properties
Labels: 🌏 Deploy

#107 [CI/CD] Deploy to EC2
  src/main/resources/application-local.properties
Labels: 🌏 Deploy

#109 [FIX] notification 제약조건 에러 해결
  src/main/java/com/gongspot/project/domain/notification/entity/Notification.java
Labels: 🐞 BugFix

#111 ♻️ Refactor: 로그인시 신규회원 및 관리자 표시되도록 수정, closes #110
  .github/workflows/deploy.yml
  src/main/java/com/gongspot/project/domain/user/entity/User.java
  src/main/java/com/gongspot/project/domain/user/repository/UserRepository.java
  src/main/java/com/gongspot/project/domain/user/service/UserService.java
  src/main/java/com/gongspot/project/global/auth/controller/AuthController.java
  src/main/java/com/gongspot/project/global/auth/dto/TokenResponseDTO.java
  src/main/java/com/gongspot/project/global/auth/oauth/CustomOAuth2SuccessHandler.java
  src/main/java/com/gongspot/project/global/auth/service/TokenService.java
  src/main/resources/application.properties
Labels: 🔨 Refactor, 🐞 BugFix

#117 [CI/CD] Deploy to EC2
  src/main/java/com/gongspot/project/domain/banner/converter/BannerConverter.java
  src/main/java/com/gongspot/project/domain/banner/dto/BannerResponseDTO.java
  src/main/java/com/gongspot/project/domain/place/controller/PlaceController.java
  src/main/java/com/gongspot/project/domain/place/converter/PlaceConverter.java
  src/main/java/com/gongspot/project/domain/place/dto/PlaceRequestDTO.java
  src/main/java/com/gongspot/project/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/gongspot/project/domain/place/entity/Place.java
  src/main/java/com/gongspot/project/domain/place/repository/PlaceRepository.java
  src/main/java/com/gongspot/project/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/gongspot/project/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/gongspot/project/domain/place/service/PlaceCommandService.java
  src/main/java/com/gongspot/project/domain/place/service/PlaceCommandServiceImpl.java
  src/main/java/com/gongspot/project/domain/place/service/PlaceQueryService.java
  src/main/java/com/gongspot/project/domain/place/service/PlaceQueryServiceImpl.java
  src/main/resources/application-local.properties
Labels: 🌏 Deploy
